# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# 
- name: "Create public"
  ansible.builtin.shell: tpm2_createprimary -c primary.ctx
  delegate_to: "{{ vm_guest_ip }}"

- name: "Read public key"
  ansible.builtin.shell: tpm2_readpublic -c primary.ctx
  delegate_to: "{{ vm_guest_ip }}"

