# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Create RSA key pair
- name: "Create a Primary Key under the Owner hierarchy of the TPM and save its context to the file primary.ctx"
  ansible.builtin.shell: tpm2_createprimary -C o -c primary.ctx
  delegate_to: "{{ vm_guest_ip }}"

- name: "Create a RSA key pair"
  ansible.builtin.shell: tpm2_create -C primary.ctx -G rsa -u rsa.pub -r rsa.priv
  delegate_to: "{{ vm_guest_ip }}"

- name: "Load RSA key pair to TPM"
  ansible.builtin.shell: tpm2_load -C primary.ctx -u rsa.pub -r rsa.priv -c rsa.ctx
  delegate_to: "{{ vm_guest_ip }}"

- name: "Prepare test data"
  ansible.builtin.shell: echo "Hello_vTPM_Signature" > test_signature_data.txt
  delegate_to: "{{ vm_guest_ip }}"

- name: "Sign the data file using TPM"
  ansible.builtin.shell: tpm2_sign -c rsa.ctx -g sha256 -o sig.dat test_signature_data.txt
  delegate_to: "{{ vm_guest_ip }}"

- name: "Verify the signature"
  ansible.builtin.shell: tpm2_verifysignature -c rsa.ctx -g sha256 -m test_signature_data.txt -s sig.dat
  delegate_to: "{{ vm_guest_ip }}"
